#pragma once

#include <cstdint>

enum PackageType : uint8_t {
    HANDSHAKE_REQUEST = 1,
    HANDSHAKE_RESPONSE = 2,
    REHANDSHAKE = 3,
    GET_PEER_REQUEST = 4,
    GET_PEER_RESPONSE = 5,
    P2P_HANDSHAKE_REQUEST = 6,
    P2P_HANDSHAKE_RESPONSE = 7,
    NAT_PROBE_REQUEST = 8,
    NAT_PROBE_RESPONSE = 9,
    KEEPALIVE = 10,
    TRANSFER_DATA = 11
};
